version: "3"
services:
    guest:
        container_name: "guest-container"
        build:
            context: .
            dockerfile: Dockerfile_guest
        ports:
        - "80:80"
        volumes:
            - type: bind
              source: "/work/guest/mnt"
              target: "/work"
        tty: true
